# Generated by Django 4.0.6 on 2022-12-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DnevnikStudenta',
            new_name='StudentDnevnik',
        ),
    ]
