# Generated by Django 4.0.6 on 2022-12-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_praksa_broj_odradenih_sati'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdnevnik',
            name='broj_kompanija',
        ),
        migrations.RemoveField(
            model_name='studentdnevnik',
            name='broj_radnih_mjesta',
        ),
        migrations.RemoveField(
            model_name='studentdnevnik',
            name='ukupni_sati_rada',
        ),
        migrations.AddField(
            model_name='studentdnevnik',
            name='prakse',
            field=models.ManyToManyField(to='main.praksa'),
        ),
    ]
