# Generated by Django 4.0.6 on 2022-12-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_studentdnevnik_broj_kompanija_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdnevnik',
            name='ukupan_broj_sati_rada',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
