# Generated by Django 4.0.6 on 2022-12-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_studentdnevnik_ukupan_broj_sati_rada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdnevnik',
            old_name='ukupan_broj_sati_rada',
            new_name='ukupan_broj_sati',
        ),
    ]
