# Generated by Django 4.0.6 on 2022-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_studentdnevnik_ukupan_broj_sati'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdnevnik',
            name='ukupni_broj_sati_rada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
